name: BCentral Integration tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environments
        run: |
          echo "Test cases are only avaiable in dev,stage,prod. master is not supported"
          exit 1

